vehicle_config:
  max_speed: 15.0             # [km/h] 
  max_accel: 1.0              # [m/s^2]
  max_steering_angle: 40.0    # [deg]
  max_lateral_accel: 1.0      # [m/s^2]
  min_turning_radius: 6.0     # [m]
  wheelbase: 2.5              # [m]
  cg_to_front: 3.2            # [m]
  cg_to_rear: 1.0             # [m]
  width: 1.8                  # [m]

env:
  dt: 0.25                    # [s]
  max_initial_position: 10.0  # [m]
  max_initial_heading: 180.0  # [deg]

reward:
  path_resolution: 0.1        # [m]
  heading_threshold: 1.0      # [deg]
  velocity_threshold: 0.5     # [km/h]
  goal_reach: 100.0           # [-]
  collision: -10000.0         # [-]

data_gen:
  num_samples: 2000
  random_seed: 42
  file_dir: "./data"
  file_name: "range_10.0_180.0_2000"